insert into Price(currency,price,vehicle_id) values('USD',2423,1)
insert into Price(currency,price,vehicle_id) values('USD',7777,2)
insert into Price(currency,price,vehicle_id) values('USD',6666,3)
insert into Price(currency,price,vehicle_id) values('USD',5555,4)
insert into Price(currency,price,vehicle_id) values('USD',4444,5)
insert into Price(currency,price,vehicle_id) values('USD',6777,6)
insert into Price(currency,price,vehicle_id) values('USD',4422,7)